// generated by generate_qobject.py (Hugo Rivera, 2016)
#include "notificationclient.h"

#if defined(Q_OS_ANDROID)
#include <QtAndroidExtras/QAndroidJniObject>
#endif

NotificationClient::NotificationClient(const QString &notification, const QString &content_title, QObject *parent)
    : QObject(parent), m_notification(notification), m_content_title(content_title)
{
#if defined(Q_OS_ANDROID)
    connect(this, SIGNAL(notificationChanged()), this, SLOT(updateAndroidNotification()));
#endif
}

void NotificationClient::setNotification(QString notification)
{
    if (notification != m_notification) {
        m_notification = notification;
        emit notificationChanged();
    }
}

void NotificationClient::setContent_title(QString content_title)
{
    if (content_title != m_content_title) {
        m_content_title = content_title;
        emit content_titleChanged();
    }
}

QString NotificationClient::notification() const
{
    return m_notification;
}

QString NotificationClient::content_title() const
{
    return m_content_title;
}

void NotificationClient::updateAndroidNotification()
{
#if defined(Q_OS_ANDROID)
    QAndroidJniObject javaNotification = QAndroidJniObject::fromString(m_notification);
    QAndroidJniObject javaContentTitle = QAndroidJniObject::fromString(m_content_title);
    QAndroidJniObject::callStaticMethod<void>("org/qtproject/example/demo/NotificationClient",
                                       "notify",
                                       "(Ljava/lang/String;Ljava/lang/String;)V",
                                       javaNotification.object<jstring>(),
                                       javaContentTitle.object<jstring>());
#endif
}
