// generated by generate_qobject.py (Hugo Rivera, 2016)
#ifndef NOTIFICATIONCLIENT_H
#define NOTIFICATIONCLIENT_H

#include <QObject>

class NotificationClient : public QObject
{
    Q_OBJECT

   Q_PROPERTY(QString notification READ notification WRITE setNotification NOTIFY notificationChanged)
   Q_PROPERTY(QString content_title READ content_title WRITE setContent_title NOTIFY content_titleChanged)

public:
    explicit NotificationClient(QObject *parent = 0);
    NotificationClient(const QString &notification, const QString &content_title, QObject *parent=0);

    void setNotification(QString notification);
    void setContent_title(QString content_title);

    QString notification() const;
    QString content_title() const;

signals:
    void notificationChanged();
    void content_titleChanged();

private slots:
    void updateAndroidNotification();

private:
    QString m_notification;
    QString m_content_title;

};

#endif // NOTIFICATIONCLIENT_H
