// generated by generate_qobject.py (Hugo Rivera, 2016)
#include "dataobject.h"

DataObject::DataObject(const QString &name, const QString &location, QObject *parent)
    : QObject(parent), m_name(name), m_location(location)
{
}

void DataObject::setName(QString name)
{
    if (name != m_name) {
        m_name = name;
        emit nameChanged(name);
    }
}

void DataObject::setLocation(QString location)
{
    if (location != m_location) {
        m_location = location;
        emit locationChanged(location);
    }
}

QString DataObject::name() const
{
    return m_name;
}

QString DataObject::location() const
{
    return m_location;
}
