// generated by generate_qobject.py (Hugo Rivera, 2016)
#ifndef DATAOBJECT_H
#define DATAOBJECT_H

#include <QObject>

class DataObject : public QObject
{
    Q_OBJECT

   Q_PROPERTY(QString name READ name WRITE setName NOTIFY nameChanged)
   Q_PROPERTY(QString location READ location WRITE setLocation NOTIFY locationChanged)

public:
    explicit DataObject(QObject *parent = 0);

    DataObject(const QString &name, const QString &location, QObject *parent=0);

    void setName(QString name);
    void setLocation(QString location);

    QString name() const;
    QString location() const;

signals:
    void nameChanged(QString);
    void locationChanged(QString);

private:
    QString m_name;
    QString m_location;

};

#endif // DATAOBJECT_H
